# Generated by Django 3.0.11 on 2020-12-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('data', models.DateField(verbose_name='дата издания')),
                ('picture', models.ImageField(upload_to='media/', verbose_name='обложка')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('picture', models.ImageField(upload_to='media/', verbose_name='аватар')),
            ],
            options={
                'verbose_name': 'исполнитель',
                'verbose_name_plural': 'исполнители',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default=1, max_length=3, verbose_name='position_in_album')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('music', models.FileField(upload_to='media/', verbose_name='песня')),
                ('album', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musics.Albums', verbose_name='альбом')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musics.Author', verbose_name='исполнитель')),
                ('category', models.ForeignKey(default='punk', on_delete=django.db.models.deletion.CASCADE, to='musics.Category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'трек',
                'verbose_name_plural': 'треки',
            },
        ),
        migrations.AddField(
            model_name='albums',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musics.Author', verbose_name='исполнитель'),
        ),
    ]
