# Generated by Django 3.0.11 on 2020-12-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_favoritemusiclist_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='favourite_music',
            new_name='favorite_music',
        ),
    ]
