# Generated by Django 3.0.11 on 2020-12-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_auto_20201223_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='favorite_music',
            field=models.ManyToManyField(default=None, to='musics.Music'),
        ),
        migrations.DeleteModel(
            name='FavoriteMusicList',
        ),
    ]
